name: Deploy Monitor API to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Artifact Registry Docker auth
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t besc-monitor-api .

    - name: Tag image
      run: |
        docker tag besc-monitor-api \
        us-central1-docker.pkg.dev/besc-475714/docker-images/besc-monitor-api:latest

    - name: Push image
      run: |
        docker push \
        us-central1-docker.pkg.dev/besc-475714/docker-images/besc-monitor-api:latest
