name: Deploy Monitor API to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Activate Service Account (fix for docker auth)
      run: gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: docker build -t besc-monitor-api .

    - name: Tag Docker image
      run: |
        docker tag besc-monitor-api \
        us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images/besc-monitor-api:latest

    - name: Push Docker image
      run: |
        docker push \
        us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images/besc-monitor-api:latest
